version: '3'
services:
  db:
    image: circleci/postgres:9.6.9-alpine
    env_file:
      - .env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/sample-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
